name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Check .NET Core version
        run: dotnet --version

      - name: Build
        run: ./build.sh

      - name: Test
        run: ./build.sh test

      - name: Archive artifacts
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: NuGet Package
          path: AWZhome.GutenTag/bin/Release/*.nupkg
